version: '3'
services:
  web:
    build: .
    ports:
    - "5000:5000"
    links: 
    - db
    - redis
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: microservice
  redis:
    image: redis
    ports: 
      - "6379:6379"
    restart: always